import React from 'react';
import { SecondHeading } from "../../global/headings/second-heading/SecondHeading";
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import style from "./steps.module.css";

export const EasySteps = () => {
    const data = [
        {
            img: "./images/steps.png",
            title: "Input Text for Analysis",
            desc: "Allow users to input text by typing, uploading a document, or providing a link. The system analyzes the provided text to determine if it's generated by AI."
        },
        {
            img: "./images/steps.png",
            title: "Analyze Text",
            desc: "Upon clicking the Detect AI button, the system processes the input text, applying detection techniques. The results are displayed, indicating whether the text is AI-generated."
        },
        {
            img: "./images/steps.png",
            title: "Enhance Human-like Quality",
            desc: "Users can choose to refine the AI-generated text to sound more human-like. By clicking the 'Rewrite AI' button, the text undergoes adjustments to improve its naturalness."
        }
    ]
    return (
        <>
            <section>
                <div className='custom-container custom_row'>
                    <SecondHeading heading={<><span className='color-green'>3</span> Easy Steps</>} />
                    <p className='text-sm color-grey text-center pt-3'>Introducing our AI plagiarism detection for AI-generated text, ensuring 95% accuracy. Elevate content authenticity, combat misinformation, and foster trust in the digital realm.</p>

                    {
                        data.map(({ img, title, desc }, i) => {
                            return (
                                <Row className={style.steps_row}>
                                    <Col key={i.toString()}>
                                        <Row className={style.steps_inner__row}>
                                            <Col className='p-0'>
                                                <img src={img} alt='' />
                                            </Col>
                                            <Col className='p-0'>
                                                <h3>{i+1}</h3>
                                                <h2>{title}</h2>
                                                <p>{desc}</p>
                                            </Col>
                                        </Row>
                                    </Col>
                                </Row>

                            )
                        })
                    }
                </div>
            </section>
        </>
    )
}